"""Write a VASP geometry-optimization input set (INCAR, KPOINTS, POSCAR).

PBE-D3BJ, fixed-cell ionic relaxation, Gaussian smearing, no CHGCAR/WAVECAR. POTCAR is left
to the user: POSCAR species are ordered lightest-to-heaviest so a concatenated POTCAR lines
up (see the POTCAR.order note written alongside). Every INCAR/KPOINTS value can be
overridden or extended from YAML via ``deep_merge``.
"""
from __future__ import annotations

from pathlib import Path

from ase import Atoms
from ase.io import write as ase_write

from .common import deep_merge, fmt_scalar, sort_by_Z

# Project-standard PBE-D3BJ geo-opt INCAR. Override any tag (or add new ones) under config
# ``dft.vasp.incar``; set a tag to ``null`` to drop it.
DEFAULT_VASP_INCAR: dict = {
    "SYSTEM": "amorphous surface oxide",
    "PREC": "Normal",
    "ENCUT": 500,          # eV plane-wave cutoff
    "ALGO": "Fast",        # electronic minimisation algorithm
    "EDIFF": 1e-5,         # eV, SCF convergence
    "EDIFFG": -0.03,       # eV/A, force-based ionic convergence
    "IBRION": 2,           # conjugate-gradient ionic relaxation
    "POTIM": 0.5,          # ionic step scaling
    "ISIF": 2,             # relax ions; cell volume & shape fixed
    "NSW": 200,            # max ionic steps
    "ISMEAR": 0,           # Gaussian smearing
    "SIGMA": 0.05,
    "ISPIN": 1,            # spin non-polarised
    "GGA": "PE",           # PBE
    "IVDW": 12,            # DFT-D3 with Becke-Johnson damping
    "LREAL": "Auto",       # real-space projection (large cells)
    "LCHARG": False,       # no CHGCAR
    "LWAVE": False,        # no WAVECAR
    "LVTOT": False,        # no LOCPOT (total local potential)
    "NWRITE": 1,           # terse OUTCAR
    "ISYM": 0,             # amorphous: no symmetry
    "NELM": 200,           # max SCF steps
}

DEFAULT_VASP_KPOINTS: dict = {"mode": "gamma", "grid": [1, 1, 1], "shift": [0, 0, 0]}


def _fmt(value) -> str:
    return fmt_scalar(value)   # VASP booleans: .TRUE. / .FALSE.


def render_incar(tags: dict) -> str:
    lines = ["# generated by AURAMAXXING"]
    lines += [f"{key} = {_fmt(val)}" for key, val in tags.items()]
    return "\n".join(lines) + "\n"


def render_kpoints(kpts: dict) -> str:
    mode = str(kpts.get("mode", "gamma")).lower()
    label = "Gamma" if mode == "gamma" else "Monkhorst"
    return (
        f"Automatic mesh ({label})\n"
        "0\n"
        f"{label}\n"
        f"{_fmt(kpts.get('grid', [1, 1, 1]))}\n"
        f"{_fmt(kpts.get('shift', [0, 0, 0]))}\n"
    )


def write_vasp_inputs(atoms: Atoms, options: dict | None, out_dir: Path) -> Path:
    """Write INCAR, KPOINTS, POSCAR (+ a POTCAR.order note) into ``out_dir``."""
    options = options or {}
    incar = deep_merge(DEFAULT_VASP_INCAR, options.get("incar"))
    kpoints = deep_merge(DEFAULT_VASP_KPOINTS, options.get("kpoints"))

    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    sorted_atoms = sort_by_Z(atoms)
    (out_dir / "INCAR").write_text(render_incar(incar))
    (out_dir / "KPOINTS").write_text(render_kpoints(kpoints))
    # vasp5 header carries the element symbols; sort=False keeps our ascending-Z order so the
    # species blocks match the user's POTCAR. FixAtoms is written as Selective Dynamics.
    ase_write(out_dir / "POSCAR", sorted_atoms, format="vasp", sort=False, vasp5=True)

    order = list(dict.fromkeys(sorted_atoms.get_chemical_symbols()))
    (out_dir / "POTCAR.order").write_text(
        "Assemble POTCAR from the PBE PAW potentials concatenated in this order:\n"
        + " ".join(order) + "\n"
    )
    return out_dir
